{"name": "test_log_in_failed", "status": "passed", "attachments": [{"name": "stdout", "source": "a15e0eb3-b958-4dee-9b75-11041a69f9b9-attachment.txt", "type": "text/plain"}], "start": 1660830098699, "stop": 1660830100000, "uuid": "37806436-8105-4282-a017-5ea454504b6d", "historyId": "ad708d544f55a014f3d73d6863640157", "testCaseId": "bd1a72a53e8e771501be030ce7fa9b32", "fullName": "test_login.TestLogIn#test_log_in_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogIn"}, {"name": "host", "value": "DESKTOP-3351BCE"}, {"name": "thread", "value": "15712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}