{"name": "test_log_in_failed", "status": "passed", "attachments": [{"name": "stdout", "source": "2f921992-38d1-46e4-b091-b743add9f534-attachment.txt", "type": "text/plain"}], "start": 1661194719282, "stop": 1661194720795, "uuid": "512660b1-2416-475d-bce2-05b635859178", "historyId": "cc79ff789f6cedde8fb5969521c36c8a", "testCaseId": "fa1497519817ecbd81b584514b07580f", "fullName": "Tests.test_login.TestLogIn#test_log_in_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogIn"}, {"name": "host", "value": "DESKTOP-3351BCE"}, {"name": "thread", "value": "820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}